### ISSUE TITLE
GCop AD0001 - ArgumentException @ CallExtensionMethodAsExtensionAnalyzer

### ISSUE THREAD

**Issue by nnpcYvIVl** [Geeksltd/GCop#154]
```
Warning	AD0001	Analyzer 'GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Inconsistent language versions
Parameter name: syntaxTrees'.	Solution		1	Active	Analyzer 'GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Solution
SyntaxTree: C:\Workspace\Solution\Library.cs
SyntaxNode: Enumerable.Concat(filelist, directorylist ... [InvocationExpressionSyntax]@[280287..280329) (6990,19)-(6990,61)

System.ArgumentException: Inconsistent language versions
Parameter name: syntaxTrees
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonLanguageVersion(ImmutableArray`1 syntaxTrees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation..ctor(String assemblyName, CSharpCompilationOptions options, ImmutableArray`1 references, CSharpCompilation previousSubmission, Type submissionReturnType, Type hostObjectType, Boolean isSubmission, ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations, AsyncQueue`1 eventQueue)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Update(ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at Microsoft.CodeAnalysis.Compilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.IsSelectingADifferentMethod(IEnumerable`1 childNodes, SimpleNameSyntax methodName, SyntaxTree tree, IMethodSymbol methodSymbol, ExpressionSyntax invocationExpression, Compilation compilation)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.Analyze(SyntaxNodeAnalysisContext context, Compilation compilation)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.<>c__DisplayClass3_0.<AnalyzeCompilation>b__0(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by Foroughi** [comment]
@nnpcYvIVl Would you please be more specific about the following questions : 

1 - Whats the context you got this error? Isn't this error pointing out to any piece of code ?! If yes, please mention that code here. 
2 - Whats the current project type? Which language are you using ?! 

Please provide these sort of information as much as you can

**Comment by nnpcYvIVl** [comment]
@Foroughi 

> 1 - Whats the context you got this error? Isn't this error pointing out to any piece of code ?! If yes, please mention that code here.

This error appears in the error list after loading the solution. This particular code file is too big to post but here is a sample repro. Make sure the Language version is set to "C# latest minor version (latest)" in advanced build settings.

```csharp
using System.Collections.Generic;
using System.Linq;

namespace GCopAD0001
{
    public class Class
    {
        public static IEnumerable<string> Method()
        {
            return Enumerable.Concat(default(IEnumerable<string>), default);
        }
    }
}
```

> 2 - Whats the current project type? Which language are you using ?!

Winforms C#.

**Comment by sungam3r** [comment]
I have the same error:
```
AD0001	Analyzer 'GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Inconsistent language versions
Parameter name: syntaxTrees'.
'Exception occurred with following context:
Compilation: Exporter.Tests
SyntaxTree: C:\Exporter.Tests\Cases\Tests.cs
SyntaxNode: Program.IsPossibleReturnType(type ... [InvocationExpressionSyntax]@[891..925) (22,120)-(22,154)

System.ArgumentException: Inconsistent language versions
Parameter name: syntaxTrees
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonLanguageVersion(ImmutableArray`1 syntaxTrees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation..ctor(String assemblyName, CSharpCompilationOptions options, ImmutableArray`1 references, CSharpCompilation previousSubmission, Type submissionReturnType, Type hostObjectType, Boolean isSubmission, ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations, AsyncQueue`1 eventQueue)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Update(ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at Microsoft.CodeAnalysis.Compilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.IsSelectingADifferentMethod(IEnumerable`1 childNodes, SimpleNameSyntax methodName, SyntaxTree tree, IMethodSymbol methodSymbol, ExpressionSyntax invocationExpression, Compilation compilation)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.Analyze(SyntaxNodeAnalysisContext context, Compilation compilation)
   at GCop.Common.Rules.Usage.CallExtensionMethodAsExtensionAnalyzer.<>c__DisplayClass3_0.<AnalyzeCompilation>b__0(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

```csharp
internal static class Program
{
    internal static bool IsPossibleReturnType(this Type type) => type == typeof(ISchema) || type == typeof(object) || typeof(ISchema).IsAssignableFrom(type);
}
```

If a full test case is required, then I can do it later.

**Comment by kmataru** [comment]
I stumbled upon same error and as weird as it seems, on my side, it was related with the fact that the projects GUIDs were changed in solution file.

Steps to reproduce:
1. Add the analyzers to netcore 2.2 project(s).
2. Upgrading Visual Studio 2019 (which now supports netcore 3.0).
3. Add a new project (automatically created a netcore 3.0 project).

#### From this point it starts throwing that kind of error.

Failed steps:
- Change the target framework of the newly crated project.
- Remove the newly crated project from solution.

Succeeded step:
- Only reverting the GUIDs spared me from headaches.

After I added the project to solution:
![Screenshot 2019-10-12 08 33 30](https://user-images.githubusercontent.com/8168616/66695808-52ea0f80-ecce-11e9-901d-1d7dfd61e754.png)

After I removed the project from solution:
![Screenshot 2019-10-12 08 36 02](https://user-images.githubusercontent.com/8168616/66695698-6d6fb900-eccd-11e9-8211-91974548adb8.png)

**Comment by Karvan** [comment]
@azadimehdi 

Could you please have a look into this and make sure we support .net core 3.0 on VS 2019 as well.

**Comment by azadimehdi** [comment]
@Karvan It works properly.

![image](https://user-images.githubusercontent.com/35523652/71593913-0edb0e00-2b4b-11ea-94bb-5aea51421c69.png)
